import os
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import torch

from config import settings
from ml.models import UNet2D
from services.preprocessor import PreprocessedImageContainer


class ModelNotAvailableError(Exception):
    """Raised when model prediction is attempted before a real model or weights
    file is registered or can be loaded.
    """

    pass


@dataclass
class ModelPredictionOutput:
    """Structured framework-agnostic output contract for model predictions.

    Encapsulates raw prediction output array, shape, execution time, and
    metadata. The output is treated as a probability map produced by the
    upstream model and must be validated before use.
    """

    raw_prediction_array: np.ndarray
    output_shape: tuple[int, ...]
    execution_time_ms: float
    num_classes: int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.metadata = dict(self.metadata or {})
        self.metadata.setdefault(
            "specification_status",
            "TEMPORARY — PENDING ML SPECIFICATION",
        )


class BaseModelAdapter(ABC):
    """Abstract base class defining the contract for all ML adapters."""

    @abstractmethod
    def predict(
        self, container: PreprocessedImageContainer
    ) -> ModelPredictionOutput:
        pass

    @abstractmethod
    def is_loaded(self) -> bool:
        pass


class UNetModelAdapter(BaseModelAdapter):
    """Concrete adapter for the actual PyTorch U-Net checkpoint.

    The checkpoint format is the one generated by backend/ml/training/train.py:
    {
        "epoch": ...,
        "model_state_dict": ...,
        "input_size": [H, W],
        "base": ..., "depth": ...,
        ...
    }
    """

    def __init__(
        self,
        checkpoint_path: str | None = None,
        device: str | None = None,
    ) -> None:
        default_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            "checkpoints",
            "best_model.pth",
        )
        self.checkpoint_path = checkpoint_path or settings.MODEL_WEIGHTS_PATH or default_path
        self.device = torch.device(
            device or ("cuda" if torch.cuda.is_available() else "cpu")
        )
        self.model: torch.nn.Module | None = None
        self.model_name = "unet2d"
        self.input_size: tuple[int, int] | None = None
        self.model_version: str | None = None
        self._load_model()

    def _resolve_model_input(self, array: np.ndarray) -> np.ndarray:
        """Normalize a preprocessed image to a single-channel 2D array."""
        arr = np.asarray(array, dtype=np.float32)

        if arr.ndim == 3:
            if arr.shape[-1] == 1:
                arr = arr[:, :, 0]
            elif arr.shape[-1] == 3:
                arr = arr.mean(axis=-1)
            elif arr.shape[0] in (1, 3):
                arr = arr.mean(axis=0)
            else:
                raise ValueError(
                    "Unsupported image tensor shape for U-Net input: "
                    f"expected (H, W, C) or (C, H, W), got {arr.shape}"
                )
        elif arr.ndim != 2:
            raise ValueError(
                f"Unsupported image array rank for U-Net input: got {arr.ndim}, "
                f"shape={arr.shape}"
            )

        if self.input_size is not None and arr.shape != self.input_size:
            # The generic backend preprocess keeps the resized image at the target
            # size already, but guard against inconsistent arrays in a transparent way.
            arr = np.asarray(arr, dtype=np.float32)
            if arr.shape != self.input_size:
                raise ValueError(
                    "U-Net input size mismatch: expected "
                    f"{self.input_size} but got {arr.shape}"
                )

        return arr.astype(np.float32, copy=False)

    def _load_model(self) -> None:
        if not self.checkpoint_path or not os.path.exists(self.checkpoint_path):
            raise ModelNotAvailableError(
                "Model weights are not configured or checkpoint is missing: "
                f"{self.checkpoint_path}"
            )

        try:
            checkpoint = torch.load(
                self.checkpoint_path,
                map_location=self.device,
                weights_only=False,
            )
        except Exception as exc:  # pragma: no cover - narrow branch checked by tests
            raise ModelNotAvailableError(
                f"Unable to load checkpoint '{self.checkpoint_path}': {exc}"
            ) from exc

        if not isinstance(checkpoint, dict):
            raise ModelNotAvailableError(
                "Checkpoint format is invalid: expected a dictionary with model_state_dict."
            )

        required_keys = {"model_state_dict", "input_size", "base", "depth"}
        missing = required_keys.difference(checkpoint.keys())
        if missing:
            raise ModelNotAvailableError(
                "Checkpoint missing required keys: "
                f"{sorted(missing)}. File: {self.checkpoint_path}"
            )

        input_size = tuple(int(v) for v in checkpoint["input_size"])
        checkpoint_base = int(checkpoint["base"])
        checkpoint_depth = int(checkpoint["depth"])

        try:
            model = UNet2D(
                in_channels=1,
                out_channels=1,
                base=checkpoint_base,
                depth=checkpoint_depth,
                input_size=input_size,
            ).to(self.device)
            model.load_state_dict(checkpoint["model_state_dict"])
            model.eval()
        except RuntimeError as exc:
            raise ModelNotAvailableError(
                f"Incompatible checkpoint '{self.checkpoint_path}' for the current "
                f"UNet2D architecture: {exc}"
            ) from exc
        except Exception as exc:
            raise ModelNotAvailableError(
                f"Could not initialize model from checkpoint '{self.checkpoint_path}': {exc}"
            ) from exc

        self.model = model
        self.input_size = input_size
        self.model_version = checkpoint.get("model_version") or (
            f"unet2d-base{checkpoint_base}-depth{checkpoint_depth}-epoch{checkpoint.get('epoch', '?')}"
        )

    def is_loaded(self) -> bool:
        return self.model is not None

    def predict(
        self, container: PreprocessedImageContainer
    ) -> ModelPredictionOutput:
        if self.model is None:
            raise ModelNotAvailableError(
                "The real U-Net model is not loaded and cannot perform inference."
            )

        arr = self._resolve_model_input(container.processed_array)
        tensor = torch.from_numpy(arr).unsqueeze(0).unsqueeze(0).to(self.device)

        start = time.perf_counter()
        with torch.no_grad():
            logits = self.model(tensor)
            probs = torch.sigmoid(logits).squeeze(0).squeeze(0).cpu().numpy().astype(np.float32)

        elapsed_ms = (time.perf_counter() - start) * 1000.0

        if probs.shape != self.input_size:
            raise ValueError(
                "Model output shape mismatch: expected "
                f"{self.input_size} but got {probs.shape}"
            )

        return ModelPredictionOutput(
            raw_prediction_array=probs,
            output_shape=tuple(probs.shape),
            execution_time_ms=float(elapsed_ms),
            num_classes=1,
            metadata={
                "framework": "pytorch",
                "model_name": self.model_name,
                "model_version": self.model_version,
                "checkpoint": self.checkpoint_path,
                "device": str(self.device),
                "input_shape": list(tensor.shape),
                "threshold": 0.5,
            },
        )


class PendingModelAdapter(BaseModelAdapter):
    """Placeholder adapter retained for compatibility with existing tests and
    explicit failure paths. It must not be used for successful live inference.
    """

    def is_loaded(self) -> bool:
        return False

    def predict(
        self, container: PreprocessedImageContainer
    ) -> ModelPredictionOutput:
        raise ModelNotAvailableError(
            "No trained ML model weights or framework adapter registered. "
            "Real model implementation is pending main branch updates from the ML team."
        )


model_adapter_service: BaseModelAdapter = PendingModelAdapter()
